version: '3.7'
services:
  mongosource:
    image: mongo:5.0.3
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword123!!
    deploy:
      resources:
        limits:
          memory: 1000M
  mongo-express-source:
    image: mongo-express:0.54.0
    restart: always
    depends_on:
      - mongosource
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword123!!
      - ME_CONFIG_MONGODB_URL=mongodb://root:mypassword123!!@mongosource:27017/
      - ME_CONFIG_MONGODB_SERVER=mongosource
      - ME_CONFIG_MONGODB_PORT=27017
    deploy:
      resources:
        limits:
          memory: 500M
